### ISSUE TITLE
Create color schema and design

### ISSUE THREAD

**Issue by MangioneAndrea** [solec0der/uml-editor#6]

**Comment by solec0der** [comment]
i added a light and dark theme with some custom colors. they can be easily changed in the vuetify.ts file. 
i also added a ThemeChangerMenu Component for easy theme switching. 

Here you can see it in action :)
https://user-images.githubusercontent.com/34732976/103159795-0d7c0a00-47ce-11eb-965a-84127d38eec1.mov
